/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


import java.awt.HeadlessException;
import javax.swing.table.DefaultTableModel;

/*
 * @author Keven Costa
 * @author Suellen Rosemberg
 * @author Thiago francelino
*/
public class GFuncionários extends javax.swing.JFrame {
    public Loja padaria;
 
    /**   
     * Creates new form GFuncionários
     * @param padaria
     */
    public GFuncionários(Loja padaria) {
        initComponents();
        this.padaria = padaria;
    }

    public GFuncionários() throws HeadlessException {
    }
 
  
    //Popula jTable de gerente, vendedores e padeiros
    public void organizar(Loja padaria){
        String[] colunas = {"ID","Nome", "Endereço","CPF" ,"SalarioBruto"};
        DefaultTableModel modelo = new DefaultTableModel(colunas, 0);
        
        if(padaria.gerentes.isEmpty()){
            modelo.addRow(new String[]{"Não há cadastro","Não há cadastro", "Não há cadastro", "Não há cadastro", "Não há cadastro"});
            tabelag.setModel(modelo);
        }else{
            for(Gerente p: padaria.gerentes){
                System.out.println("\n\n"  + p.getNome() + "\nTá imprimindo essa poha então está salvando!!\n");
                modelo.addRow(new String[]{Integer.toString(p.id), p.getNome(), p.getEndereco(), p.getCpf(), Float.toString(p.getSalarioBruto())});
                
                tabelag.setModel(modelo); 
            } 
        }
        
        DefaultTableModel modelo1 = new DefaultTableModel(colunas, 0);
        if(padaria.vendedores.isEmpty()){
            modelo1.addRow(new String[]{"Não há cadastro","Não há cadastro", "Não há cadastro", "Não há cadastro", "Não há cadastro"});
            tabelav.setModel(modelo1);
        }else{
            for(Vendedor v: padaria.vendedores){
                modelo1.addRow(new String[]{Integer.toString(v.id), v.getNome(), v.getEndereco(), v.getCpf(), Float.toString(v.getSalarioBruto())});
                tabelav.setModel(modelo1);}
        }
        DefaultTableModel modelo2 = new DefaultTableModel(colunas, 0);
        if(padaria.padeiros.isEmpty()){
            modelo2.addRow(new String[]{"Não há cadastro","Não há cadastro", "Não há cadastro", "Não há cadastro", "Não há cadastro"});
            tabelap.setModel(modelo2);
        }else{
            for(Padeiro g: padaria.padeiros){
                
                modelo2.addRow(new String[]{Integer.toString(g.id), g.getNome(), g.getEndereco(), g.getCpf(), Float.toString(g.getSalarioBruto())});
                tabelap.setModel(modelo2);}
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Titulo = new javax.swing.JLabel();
        atualizar = new javax.swing.JButton();
        Cadastrar = new javax.swing.JButton();
        Editar = new javax.swing.JButton();
        Voltar = new javax.swing.JButton();
        Tabela = new javax.swing.JTabbedPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        tabelap = new javax.swing.JTable();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelav = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelag = new javax.swing.JTable();
        fpagamento = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        Titulo.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        Titulo.setText("Gestão de Funcionários");

        atualizar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        atualizar.setText("Atualizar");
        atualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atualizarActionPerformed(evt);
            }
        });

        Cadastrar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Cadastrar.setText("Cadastrar");
        Cadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadastrarActionPerformed(evt);
            }
        });

        Editar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Editar.setText("Editar");
        Editar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EditarMouseClicked(evt);
            }
        });
        Editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditarActionPerformed(evt);
            }
        });

        Voltar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Voltar.setText("Voltar");
        Voltar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                VoltarMouseClicked(evt);
            }
        });
        Voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VoltarActionPerformed(evt);
            }
        });

        tabelap.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Nome", "Endereco", "CPF", "SalarioBruto"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Float.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tabelap);

        Tabela.addTab("Padeiros", jScrollPane3);

        tabelav.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Nome", "Endereço", "CPF", "Salário Bruto"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Float.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabelav);

        Tabela.addTab("Vendedores", jScrollPane1);

        tabelag.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                { new Integer(1), "JEfferson", "Dos Andradas", "121.121.121-28",  new Float(12100.5)},
                {null, "", null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Nome", "Endereço", "CPF", "SalarioBruto"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Float.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tabelag);
        if (tabelag.getColumnModel().getColumnCount() > 0) {
            tabelag.getColumnModel().getColumn(0).setHeaderValue("ID");
            tabelag.getColumnModel().getColumn(1).setHeaderValue("Nome");
            tabelag.getColumnModel().getColumn(2).setHeaderValue("Endereço");
            tabelag.getColumnModel().getColumn(3).setHeaderValue("CPF");
            tabelag.getColumnModel().getColumn(4).setHeaderValue("SalarioBruto");
        }

        Tabela.addTab("Gerentes", jScrollPane2);

        fpagamento.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        fpagamento.setText("Folha de pagamento");
        fpagamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fpagamentoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Cadastrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(atualizar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Editar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Voltar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(fpagamento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 100, Short.MAX_VALUE)
                        .addComponent(Titulo)
                        .addGap(161, 161, 161))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(Tabela, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(Cadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Editar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(fpagamento, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 122, Short.MAX_VALUE)
                .addComponent(atualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Voltar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Titulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Tabela, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        setSize(new java.awt.Dimension(639, 467));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    //Atualiza a jTable
    private void atualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atualizarActionPerformed
        organizar(this.padaria);
    }//GEN-LAST:event_atualizarActionPerformed

    //Volta para inicio
    private void VoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VoltarActionPerformed
        Principal principal = new Principal(this.padaria);
        principal.setVisible(true);
        dispose();
    }//GEN-LAST:event_VoltarActionPerformed

    //Abre tela de cadastro
    private void CadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadastrarActionPerformed
        Cadastrarfuncionario cadastro = new Cadastrarfuncionario(padaria);
        cadastro.setVisible(true);
    }//GEN-LAST:event_CadastrarActionPerformed

    //Popula jTable ao abrir tela
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        organizar(padaria);
    }//GEN-LAST:event_formWindowOpened

    private void EditarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EditarMouseClicked
        
    }//GEN-LAST:event_EditarMouseClicked

    //Abre tela de folha de pagamento
    private void fpagamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fpagamentoActionPerformed
           folhadepagamento folha = new folhadepagamento(padaria);
           folha.setVisible(true);
           dispose();
    }//GEN-LAST:event_fpagamentoActionPerformed

    private void VoltarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VoltarMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_VoltarMouseClicked

    private void EditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EditarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cadastrarfuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cadastrarfuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cadastrarfuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cadastrarfuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new Gfuncionários().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Cadastrar;
    private javax.swing.JButton Editar;
    private javax.swing.JTabbedPane Tabela;
    private javax.swing.JLabel Titulo;
    private javax.swing.JButton Voltar;
    private javax.swing.JButton atualizar;
    private javax.swing.JButton fpagamento;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable tabelag;
    private javax.swing.JTable tabelap;
    private javax.swing.JTable tabelav;
    // End of variables declaration//GEN-END:variables
}
