/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Keven Costa
 * @author Suellen Rosemberg
 * @author Thiago francelino
 */
public class Principal extends javax.swing.JFrame {
    Loja padaria = new Loja();  
            
    /**
     * Creates new form Principal
     */
    public Principal(){
        initComponents();
    }
    
    public Principal(Loja padaria) {
        initComponents();
        this.padaria = padaria;
        
    }
       
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    public static void cadastrarFuncionariosEProdutos(Loja padaria){
        System.out.println("PQ");
        Gerente g = new Gerente("João","Rua: Nanci, Bairro: Serra Azul, Número: 188", "080.866.432-90", 6000);
        Vendedor v1 = new Vendedor("Mateus","Rua: Hugo Martins, Bairro: Jardim das Oliveiras, Número: 190", "557.877.402-70", 2000);
        Vendedor v2 = new Vendedor("José","Rua: Pontal, Bairro: Parque Sol Nascente, Número: 100", "035.866.432-50", 2100);
        Vendedor v3 = new Vendedor("Vitor","Rua: Santa Dorotéia, Bairro: Monte Videl, Número: 23", "060.866.432-10", 2200);
        Padeiro p = new Padeiro("João","Rua: Julio Cabral , Bairro: Raiz Nova, Número: 175", "090.806.932-20", 1000);

        padaria.gerentes.add(g);
        padaria.vendedores.add(v1);
        padaria.vendedores.add(v2);
        padaria.vendedores.add(v3);
        padaria.padeiros.add(p);
       
        ProdutoPerecivel pp1 = new ProdutoPerecivel("Arroz", 14, "Joaozinho", "11/12/2019");
        ProdutoPerecivel pp2 = new ProdutoPerecivel("Feijão", 10, "Vô Sidi", "20/07/2020");
        ProdutoPerecivel pp3 = new ProdutoPerecivel("Macarrão", 8, "Fuigini", "14/03/2021");
        ProdutoPerecivel pp4 = new ProdutoPerecivel("Leite", 5, "Dedê", "04/10/2022");
        ProdutoPerecivel pp5 = new ProdutoPerecivel("Molho de Tomate", 3, "Quero", "08/09/2019");
        ProdutoPerecivel pp6 = new ProdutoPerecivel("KetChup", 9, "Hinez", "15/01/2020");
        ProdutoPerecivel pp7 = new ProdutoPerecivel("Pão de Forma", 10, "Chumbinho", "09/11/2021");
        ProdutoPerecivel pp8 = new ProdutoPerecivel("Creme de Leite", 2, "Cremoso", "17/06/2022");
        ProdutoPerecivel pp9 = new ProdutoPerecivel("Danone", 15, "Danete", "01/08/2019");
        ProdutoPerecivel pp10 = new ProdutoPerecivel("Manteiga", 20, "Avianca", "28/04/2020");
                 
        padaria.produtosPereciveis.add(pp1);
        padaria.produtosPereciveis.add(pp2);
        padaria.produtosPereciveis.add(pp3);
        padaria.produtosPereciveis.add(pp4);
        padaria.produtosPereciveis.add(pp5);
        padaria.produtosPereciveis.add(pp6);
        padaria.produtosPereciveis.add(pp7);
        padaria.produtosPereciveis.add(pp8);
        padaria.produtosPereciveis.add(pp9);
        padaria.produtosPereciveis.add(pp10);
                 
        ProdutoNaoPerecivel pnp1 = new ProdutoNaoPerecivel("Copo", 5, "Vidro");
        ProdutoNaoPerecivel pnp2 = new ProdutoNaoPerecivel("Toalha", 10, "Pano");
        ProdutoNaoPerecivel pnp3 = new ProdutoNaoPerecivel("Bandeja", 30, "Aço");
        ProdutoNaoPerecivel pnp4 = new ProdutoNaoPerecivel("Durex", 5, "Duplex");
        ProdutoNaoPerecivel pnp5 = new ProdutoNaoPerecivel("Tesoura",25, "Inox");
        ProdutoNaoPerecivel pnp6 = new ProdutoNaoPerecivel("Revista", 15, "Cremoso");
        ProdutoNaoPerecivel pnp7 = new ProdutoNaoPerecivel("Sacola Plástica", 1, "Plastil");
        ProdutoNaoPerecivel pnp8 = new ProdutoNaoPerecivel("Borracha", 3, "Faber");
        ProdutoNaoPerecivel pnp9 = new ProdutoNaoPerecivel("Caneta", 4, "Bic");
        ProdutoNaoPerecivel pnp10 = new ProdutoNaoPerecivel("Lápis", 3, "Faber Castel");
                 
        padaria.produtosNaoPereciveis.add(pnp1);
        padaria.produtosNaoPereciveis.add(pnp2);
        padaria.produtosNaoPereciveis.add(pnp3);
        padaria.produtosNaoPereciveis.add(pnp4);
        padaria.produtosNaoPereciveis.add(pnp5);
        padaria.produtosNaoPereciveis.add(pnp6);
        padaria.produtosNaoPereciveis.add(pnp7);
        padaria.produtosNaoPereciveis.add(pnp8);
        padaria.produtosNaoPereciveis.add(pnp9);
        padaria.produtosNaoPereciveis.add(pnp10);
        
    }
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jFrame1 = new javax.swing.JFrame();
        jLabel1 = new javax.swing.JLabel();
        Botaovendas = new javax.swing.JToggleButton();
        Botaoclientes = new javax.swing.JToggleButton();
        BotaoFuncionarios = new javax.swing.JToggleButton();
        Botaoestoque = new javax.swing.JToggleButton();
        Botaoinformações = new javax.swing.JToggleButton();
        Botaoimpostos = new javax.swing.JToggleButton();

        jLabel2.setText("jLabel2");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setText("Padaria do Jorge Padeiro");

        Botaovendas.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Botaovendas.setText("Vendas");
        Botaovendas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaovendasActionPerformed(evt);
            }
        });

        Botaoclientes.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Botaoclientes.setText("Gestão de clientes");
        Botaoclientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoclientesActionPerformed(evt);
            }
        });

        BotaoFuncionarios.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        BotaoFuncionarios.setText("Gestão de Funcionários");
        BotaoFuncionarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoFuncionariosActionPerformed(evt);
            }
        });

        Botaoestoque.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Botaoestoque.setText("Estoque");
        Botaoestoque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoestoqueActionPerformed(evt);
            }
        });

        Botaoinformações.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Botaoinformações.setText("Gestão de Informações");
        Botaoinformações.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoinformaçõesActionPerformed(evt);
            }
        });

        Botaoimpostos.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Botaoimpostos.setText("Gestão de impostos");
        Botaoimpostos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoimpostosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Botaovendas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Botaoclientes, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Botaoimpostos)
                            .addComponent(Botaoestoque, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(58, 58, 58))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(BotaoFuncionarios, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(Botaoinformações, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(33, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Botaovendas, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Botaoestoque, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Botaoimpostos, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Botaoclientes, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(BotaoFuncionarios, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                    .addComponent(Botaoinformações, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(65, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(416, 356));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BotaovendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaovendasActionPerformed

        GVenda vendas = new GVenda(padaria);
        vendas.setVisible(true);
        dispose();
    }//GEN-LAST:event_BotaovendasActionPerformed

    private void BotaoestoqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoestoqueActionPerformed
        GEstoque estoque = new GEstoque(padaria);
        estoque.setVisible(true);
        dispose();
        
    }//GEN-LAST:event_BotaoestoqueActionPerformed

    private void BotaoimpostosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoimpostosActionPerformed
        GImpostos impostos = new GImpostos(padaria);
        impostos.setVisible(true);
        dispose();
        
    }//GEN-LAST:event_BotaoimpostosActionPerformed

    private void BotaoFuncionariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoFuncionariosActionPerformed
        GFuncionários funcionarios = new GFuncionários(padaria);
        funcionarios.setVisible(true);
        dispose();
    }//GEN-LAST:event_BotaoFuncionariosActionPerformed

    private void BotaoclientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoclientesActionPerformed
       GCliente cliente = new GCliente(padaria);
       cliente.setVisible(true);
       dispose();
    }//GEN-LAST:event_BotaoclientesActionPerformed

     
        
    private void BotaoinformaçõesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoinformaçõesActionPerformed
        GInformacoes informacoes = new GInformacoes(padaria);
        informacoes.setVisible(true);
        dispose();
    }//GEN-LAST:event_BotaoinformaçõesActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        cadastrarFuncionariosEProdutos(padaria);
    }//GEN-LAST:event_formComponentShown

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton BotaoFuncionarios;
    private javax.swing.JToggleButton Botaoclientes;
    private javax.swing.JToggleButton Botaoestoque;
    private javax.swing.JToggleButton Botaoimpostos;
    private javax.swing.JToggleButton Botaoinformações;
    private javax.swing.JToggleButton Botaovendas;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
